name: "Sample Action"
description: "A sample reusable action"
inputs:
  name:
    description: "Name to greet"
    required: true
    default: "World"
runs:
  using: "composite"
  steps:
    - run: echo "Hello, ${{ inputs.name }} from GitHub Actions!"
      shell: bash