name: deploy_run_postman

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
      username:
        description: "Username for API access"
        required: true
        default: "testuser"
      base_url:
        description: "Base URL for the environment"
        required: true
        default: "https://api.example.com"

jobs:
  deploy-app:
    name: Deploy Application
    uses: jackcloudgit/library/.github/workflows/reusable-deploy.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    environment: ${{ github.event.inputs.environment }}  # 👈 Enables deployment tracking

  call-postman-workflow:
    name: Run Postman Tests
    uses: jackcloudgit/library/.github/workflows/run-postman_simplified.yml@main
    needs: deploy-app
    if: ${{ success() }}
    with:
      job_name: "test-api-${{ github.event.inputs.environment }}"
      environment: ${{ github.event.inputs.environment }}
      username: "${{ github.event.inputs.username }}"
      base_url: "${{ github.event.inputs.base_url }}"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    environment: ${{ github.event.inputs.environment }}  # 👈 Enables deployment tracking
