name: deploy_run_postman
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
      username:
        description: "Username for API access"
        required: true
        default: "testuser"
      base_url:
        description: "Base URL for the environment"
        required: true
        default: "https://api.example.com"
jobs:
  deploy-app:
    name: Deploy Application
    uses: jackcloudgit/library/.github/workflows/reusable-deploy-test.yml@main
    with:
      environment: "dev"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  call-postman-workflow:
    uses: jackcloudgit/library/.github/workflows/run-postman_simplified.yml@main
    needs: deploy-app  # Wait for deploy to finish
    if: ${{ success() }}  # Run only if deploy-app succeeds
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      job_name: "test-api-${{ github.event.inputs.environment }}"
      environment: ${{ github.event.inputs.environment }}
      username: "${{ github.event.inputs.username }}"
      base_url: "${{ github.event.inputs.base_url }}"
