name: On Deployment Success

on:
  deployment_status:

jobs:
  after-deploy:
    if: >
      github.event.deployment_status.state == 'success' &&
      github.event.deployment.environment == 'your-environment-name'
    runs-on: ubuntu-latest
    steps:
      - name: Do something after successful deployment
        run: echo "Deployment to your-environment-name was successful!