name: Postman Sample Test simplified
on: [push, workflow_dispatch]

jobs:
  call-postman-workflow:
    uses: jackcloudgit/library/.github/workflows/run-postman_simplified.yml@main
    with:
      job_name: "test-api-dev"