name: Postman Sample Test simplified
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
      username:
        description: "Username for API access"
        required: true
        default: "testuser"
      base_url:
        description: "Base URL for the environment"
        required: true
        default: "https://api.example.com"
jobs:
  call-postman-workflow:
    uses: jackcloudgit/library/.github/workflows/run-postman_simplified.yml@main
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      job_name: "test-api-${{ github.event.inputs.environment }}"
      environment: ${{ github.event.inputs.environment }}
      username: "${{ github.event.inputs.username }}"
      base_url: "${{ github.event.inputs.base_url }}"      