name: Trigger Postman on Dev env success
on:
  deployment_status:

jobs:
  Trigger_Postman:
    if: >
      github.event.deployment_status.state == 'success' &&
      github.event.deployment.environment == 'Dev'
    runs-on: ubuntu-latest
    steps:
      - name: Do something after successful deployment
        run: echo "Deployment to your-environment-name was successful!"

  call-postman-workflow:
    uses: jackcloudgit/library/.github/workflows/run-postman_simplified.yml@main
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      job_name: "test-api-${{ github.event.inputs.environment }}"
      environment: ${{ github.event.inputs.environment }}
      username: "${{ github.event.inputs.username }}"
      base_url: "${{ github.event.inputs.base_url }}"