name: Trigger Postman on Dev env success

on:
  deployment_status:

jobs:
  call-postman-workflow:
    if: >
      github.event.deployment_status.state == 'success' &&
      github.event.deployment.environment == 'Dev'
    uses: jackcloudgit/library/.github/workflows/run-postman_simplified.yml@main
    with:
      job_name: "test-api-Dev"
      environment: "Dev"
      username: "${{ github.event.deployment.payload.username }}"
      base_url: "${{ github.event.deployment.payload.base_url }}"
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}